package org.oot.vr;

import android.os.Bundle;
import android.util.Log;

import org.libsdl.app.SDLActivity;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * Quest entry point.
 *
 * Deliberately thin. linkzenic's phone port carries ~1500 lines here because it has to be a
 * self-service app: an on-device ROM picker, an extraction progress dialog, and an on-screen
 * touch overlay, all wired to thirteen JNI methods.
 *
 * None of that applies to a private headset build. The ROM never reaches the device - oot.o2r is
 * generated by a host build and pushed with adb - and input arrives through OpenXR actions, not
 * a touchscreen. What is left is: make sure soh.o2r is where the game looks for it, and hand over
 * to SDL.
 *
 * No storage permission either. libultraship locates its data with
 * SDL_AndroidGetExternalStoragePath(), which is the app-private external directory - readable and
 * writable with no permission at all, and adb-reachable. The reference port needs
 * MANAGE_EXTERNAL_STORAGE only because it hardcodes /storage/emulated/0/SOH and then has to patch
 * libultraship to make that configurable. Nothing here has to.
 */
public class MainActivity extends SDLActivity {

    private static final String TAG = "OoTVR";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Must match SDL_AndroidGetExternalStoragePath(), which is what libultraship asks for:
        //   /sdcard/Android/data/org.oot.vr/files
        File root = getExternalFilesDir(null);
        if (root == null) {
            Log.e(TAG, "External files dir unavailable");
        } else {
            copyAssetIfMissing("soh.o2r", new File(root, "soh.o2r"));
            // RunExtract() checks for an assets/ directory on EVERY launch, before it looks at
            // whether an archive is already present - and if it is missing it registers a modal
            // and spins in its own draw loop waiting for an OK that a VR build can never deliver.
            // The directory has to exist even though on-device extraction never runs here.
            copyAssetTree("assets", new File(root, "assets"));
        }
        super.onCreate(savedInstanceState);
    }

    /** Recursively unpack an APK asset directory, skipping anything already on disk. */
    private void copyAssetTree(String assetDir, File target) {
        try {
            String[] entries = getAssets().list(assetDir);
            if (entries == null || entries.length == 0) {
                return; // a file, not a directory
            }
            if (!target.exists() && !target.mkdirs()) {
                Log.e(TAG, "Could not create " + target);
                return;
            }
            for (String entry : entries) {
                String childAsset = assetDir + "/" + entry;
                File childTarget = new File(target, entry);
                String[] grandchildren = getAssets().list(childAsset);
                if (grandchildren != null && grandchildren.length > 0) {
                    copyAssetTree(childAsset, childTarget);
                } else {
                    copyAssetIfMissing(childAsset, childTarget);
                }
            }
        } catch (IOException e) {
            Log.w(TAG, "Could not unpack " + assetDir + " (" + e.getMessage() + ")");
        }
    }

    /**
     * soh.o2r holds the PORT's assets and rides inside the APK; oot.o2r holds the GAME's and never
     * does. Copying only when absent keeps a hand-pushed replacement from being overwritten on
     * every launch.
     */
    private void copyAssetIfMissing(String assetName, File target) {
        if (target.exists()) {
            return;
        }
        try (InputStream in = getAssets().open(assetName);
             OutputStream out = new FileOutputStream(target)) {
            byte[] buf = new byte[1 << 16];
            int n;
            while ((n = in.read(buf)) > 0) {
                out.write(buf, 0, n);
            }
            Log.i(TAG, "Copied " + assetName + " to " + target);
        } catch (IOException e) {
            // Not fatal: the build may simply not bundle it yet, and the game reports the miss.
            Log.w(TAG, "No bundled " + assetName + " (" + e.getMessage() + ")");
        }
    }
}
